name:                aoc21
version:             0.1.0.0
github:              "bthuliot/aoc21"
license:             GPL-3
author:              "Bryce Thuilot"
maintainer:          "bryce@thuilot.io"
copyright:           "2021 Bryce Thuilot"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Advent of Code 2021
category:            Challenge

description:         Please see the README on GitHub at <https://github.com/bthuliot/aoc21#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

executables:
  aoc2021:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc21

tests:
  aoc2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc21
